name: Check modified notebooks

on:
  pull_request:
    paths:
      - quri_sdk_notebook/**.ipynb

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: |
        poetry install

    - run: |
        make execute-in-place
    
    - run: |
        make clean-nb
        
    - run: |
        git diff --exit-code
